app:
  name: airqo-meta-data-api
  label: meta-data-api
  namespace: production
  configmap: prod-meta-data-api-config

replicaCount: 3

images:
  repositories:
    api: gcr.io/airqo-250220/airqo-meta-data-api
    sitesConsumer: gcr.io/airqo-250220/airqo-meta-data-sites-consumer
  tag: latest

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  limits:
    cpu: 1000m
    memory: 500Mi
  requests:
    # Average usage was 0.1 vCPU and 250Mi over the last 7 days
    cpu: 100m
    memory: 250Mi

volumeMounts:
  - name: config-volume
    mountPath: /etc/config

volumes:
  - name: config-volume
    configMap:
      name: prod-meta-data-api-config-files

ingress:
  enabled: false

service:
  type: NodePort
  port: 4001
  protocol: TCP
  targetPort: 4001

autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  # targetMemoryUtilizationPercentage: 70
