app:
  name: airqo-stage-meta-data-api
  label: meta-data-api
  namespace: staging
  configmap: stage-meta-data-api-config
replicaCount: 2
images:
  repositories:
    api: eu.gcr.io/airqo-250220/airqo-stage-meta-data-api
    sitesConsumer: eu.gcr.io/airqo-250220/airqo-stage-meta-data-sites-consumer
  tag: stage-d6009c1d-1677682538
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
resources:
  limits:
    cpu: 300m
    memory: 400Mi
  requests:
    cpu: 100m
    memory: 200Mi
volumeMounts:
  - name: config-volume
    mountPath: /etc/config
volumes:
  - name: config-volume
    configMap:
      name: stage-meta-data-api-config-files
ingress:
  enabled: false
service:
  type: NodePort
  port: 4001
  protocol: TCP
  targetPort: 4001
autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
