app:
  name: airqo-stage-meta-data-api
  label: meta-data-api
  namespace: staging
  configmap: stage-meta-data-api-config

replicaCount: 2

images:
  repositories:
    api: gcr.io/airqo-250220/airqo-stage-meta-data-api
    sitesConsumer: gcr.io/airqo-250220/airqo-meta-data-sites-consumer
  tag: latest

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  limits:
    cpu: 300m
    memory: 400Mi
  requests:
    # Average usage was 0.1 vCPU and 200Mi over the last 7 days
    cpu: 100m
    memory: 200Mi

volumeMounts:
  - name: config-volume
    mountPath: /etc/config

volumes:
  - name: config-volume
    configMap:
      name: stage-meta-data-api-config-files

ingress:
  enabled: false

service:
  type: NodePort
  port: 4001
  protocol: TCP
  targetPort: 4001

autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
