apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-view-message-broker
  namespace: production
spec:
  selector:
    matchLabels:
      app: view-message-broker
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: view-message-broker
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - high-memory
            - weight: 1
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - general-purpose
      containers:
        - name: view-message-broker
          image: eu.gcr.io/airqo-250220/airqo-view-message-broker:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: prod-view-message-broker-config
          resources:
            requests:
              # Average usage was 0.008 vCPU and 200Mi over the last 30 days
              cpu: 10m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 400Mi
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: view-api-config-files
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: airqo-view-message-broker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airqo-view-message-broker
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
