nameOverride: ''
fullnameOverride: ''
namespace: production
images:
  repositories:
    api: eu.gcr.io/airqo-250220/airqo-view-api
  tag: prod-a4713257-1690183591
api:
  name: airqo-view-api
  label: view-api
  configmap: prod-view-api-config
  replicaCount: 2
  podAnnotations: {}
  resources:
    limits:
      cpu: 100m
      memory: 1500Mi
    requests:
      cpu: 10m
      memory: 500Mi
ingress:
  enabled: false
service:
  type: NodePort
  port: 8080
  protocol: TCP
  targetPort: 8080
autoscaling:
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
