app:
  name: prod-fault-detection-api
  label: fault-detection
  namespace: production
  configmap: prod-fault-detection-api-config

initContainers:
  container1:
    image:
      repository: gcr.io/airqo-250220/prod-train-catboost-model
      tag: latest
  container2:
    image:
      repository: gcr.io/airqo-250220/prod-train-lstm-model
      tag: latest

replicaCount: 2

image:
  repository: gcr.io/airqo-250220/stage-fault-detection-api
  tag: latest

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  limits:
    cpu: 500m
    memory: 300Mi
  requests:
    # Average usage was 0.1 vCPU and 200Mi over the last 30 days
    cpu: 100m
    memory: 200Mi

volumeMounts:
  - name: shared-data
    mountPath: /usr/models

volumes:
  - name: shared-data
    emptyDir: {}

ingress:
  enabled: false

service:
  type: NodePort
  port: 4001
  protocol: TCP
  targetPort: 4001
  nodePort: 30013

autoscaling:
  minReplicas: 1
  maxReplicas: 3
  # targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
