apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: airqo-redis-server
  name: airqo-redis-server
  namespace: staging
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      io.kompose.service: airqo-redis-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: airqo-redis-server
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - general-purpose
      containers:
        - env:
            - name: GET_HOSTS_FROM
              value: dns
          image: us.gcr.io/airqo-250220/airqo-stage-redis-server:latest
          imagePullPolicy: Always
          name: airqo-redis-server
          ports:
            - containerPort: 6379
          resources:
            requests:
              # Average usage was 0.001 vCPU and 10Mi over the last 30 days
              cpu: 5m
              memory: 10Mi
            limits:
              cpu: 50m
              memory: 50Mi
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: airqo-redis-server
  name: airqo-redis-server
  namespace: staging
spec:
  ports:
    - name: airqo-redis-server
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: airqo-redis-server
status:
  loadBalancer: {}

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: airqo-redis-server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airqo-redis-server
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
