apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: nginx-ingress
type: kubernetes.io/tls
data:
  # This is strictly a template file for a kubernetes secret and
  # thus values herein should never be left in file or committed!
  tls.crt: |
    << TLS certificated data here >>
  tls.key: |
    << TLS private key data here >>
