apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: "2020-08-13T11:00:12Z"
  managedFields:
    - apiVersion: batch/v1
      manager: kubectl
      operation: Update
      time: "2020-08-13T11:00:12Z"
  name: stage-gpmodel
  namespace: staging
spec:
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: airqo-stage-gpmodel
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 10
                  preference:
                    matchExpressions:
                      - key: node-type
                        operator: In
                        values:
                          - compute
          containers:
            - name: airqo-stage-gpmodel
              image: us.gcr.io/airqo-250220/airqo-stage-gp-model-job:latest
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: env-gp-model-staging
              resources:
                limits:
                  cpu: 1000m
                  memory: 4000Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 0 * * * *
  suspend: false
status: {}
