app:
  name: prod-gpmodel
  cronJobName: prod-gpmodel-cron-job
  label: gpmodel
  namespace: production
  configMap: env-gp-model-production
images:
  tag: prod-a4713257-1690183591
  repositories:
    cronJob: eu.gcr.io/airqo-250220/airqo-gp-model-job
nameOverride: ''
fullnameOverride: ''
podAnnotations: {}
resources:
  limits:
    cpu: 2000m
    memory: 4000Mi
  requests:
    cpu: 50m
    memory: 100Mi
volumeMounts:
  - name: config-volume
    mountPath: /etc/config
volumes:
  - name: config-volume
    configMap:
      name: gp-model-job-config-files
