app:
  name: stage-gpmodel
  cronJobName: stage-gpmodel-cron-job
  brokerConsumerName: stage-gpmodel-broker-consumer
  label: gpmodel
  namespace: staging
  configMap: env-gp-model-staging
replicaCount: 1
images:
  tag: stage-948d4315-1680198467
  pullPolicy: IfNotPresent
  repositories:
    cronJob: eu.gcr.io/airqo-250220/airqo-stage-gp-model-job
    brokerConsumer: eu.gcr.io/airqo-250220/airqo-stage-gp-model-broker-consumer

nameOverride: ''
fullnameOverride: ''
podAnnotations: {}
resources:
  limits:
    cpu: 1000m
    memory: 4000Mi
  requests:
    cpu: 50m
    memory: 100Mi
