app:
  name: stage-analytics-report-job
  namespace: staging
  configmap: env-analytics-report-staging

image:
  repository: gcr.io/airqo-250220/airqo-stage-analytics-report-job
  tag: latest

nameOverride: ""
fullnameOverride: ""
resources:
  limits:
    cpu: 1000m
    memory: 4000Mi

volumeMounts:
  - name: config-volume
    mountPath: /etc/config

volumes:
  - name: config-volume
    configMap:
      name: env-analytics-report-staging-files
