app:
  name: prod-analytics-report-job
  namespace: production
  configmap: env-analytics-report-production

image:
  repository: gcr.io/airqo-250220/airqo-analytics-report-job
  tag: latest

nameOverride: ""
fullnameOverride: ""
resources:
  limits:
    cpu: 1000m
    memory: 4000Mi

volumeMounts:
  - name: config-volume
    mountPath: /etc/config

volumes:
  - name: config-volume
    configMap:
      name: env-analytics-report-production-files
