apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-data-mgt-api
  namespace: production
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: airqo-data-mgt-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: airqo-data-mgt-api
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - general-purpose
            - weight: 1
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - high-memory
      containers:
        - name: airqo-data-mgt-api
          image: eu.gcr.io/airqo-250220/airqo-data-mgt-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3000
          #   initialDelaySecond: 5
          #   periodSeconds: 3
          #   successThreshold: 1
          envFrom:
            - configMapRef:
                name: data-mgt-api-config
          resources:
            requests:
              # Average usage was 0.0005 vCPU and 80Mi over the last 30 days
              cpu: 5m
              memory: 70Mi
            limits:
              cpu: 50m
              memory: 120Mi
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: airqo-data-mgt-api-svc
  namespace: production
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    app: airqo-data-mgt-api
  type: NodePort

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: airqo-data-mgt-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airqo-data-mgt-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memorycpu
        target:
          type: Utilization
          averageUtilization: 70
