namespace: staging
nameOverride: ''
fullnameOverride: ''
images:
  repositories:
    api: eu.gcr.io/airqo-250220/airqo-stage-analytics-api
    celery: eu.gcr.io/airqo-250220/airqo-stage-analytics-celery
  tag: stage-5c6990cd-1719227902
api:
  name: airqo-stage-analytics-api
  label: sta-alytics-api
  configmap: env-analytics-staging
  replicaCount: 2
  podAnnotations: {}
  resources:
    limits:
      cpu: 100m
      memory: 600Mi
    requests:
      cpu: 10m
      memory: 250Mi
volumeMounts:
  - name: config-volume
    mountPath: /etc/config
volumes:
  - name: config-volume
    configMap:
      name: stage-analytics-config-files
service:
  type: NodePort
  port: 5000
  protocol: TCP
  targetPort: 5000
  nodePort: 31003
ingress:
  enabled: false
autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetMemoryUtilizationPercentage: 80
