###########################################################
# Start deployment of device-monitoring microservice
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-device-monitor-api
  namespace: production
spec:
  selector:
    matchLabels:
      app: device-monitor-api
  replicas: 3
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: device-monitor-api
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - general-purpose
            - weight: 1
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - high-memory
      containers:
        - name: dev-monitor-api
          image: eu.gcr.io/airqo-250220/airqo-device-monitor-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4001
              name: dev-monitor-api
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 4001
          #   initialDelaySecond: 5
          #   periodSeconds: 3
          #   successThreshold: 1
          envFrom:
            - configMapRef:
                name: env-device-monitoring-production
          resources:
            requests:
              # Average usage was 0.0005 vCPU and 50Mi over the last 30 days
              cpu: 5m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 100Mi

---
kind: Service
apiVersion: v1
metadata:
  name: airqo-device-monitor-api-svc
  namespace: production
spec:
  selector:
    app: device-monitor-api
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
      nodePort: 30006
  type: NodePort

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: airqo-device-monitor-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airqo-device-monitor-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
