apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: "2020-08-13T11:00:12Z"
  managedFields:
    - apiVersion: batch/v1
      manager: kubectl
      operation: Update
      time: "2020-08-13T11:00:12Z"
  name: prod-device-status-job
  namespace: production
spec:
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: prod-device-status-job
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 10
                  preference:
                    matchExpressions:
                      - key: node-type
                        operator: In
                        values:
                          - compute
          containers:
            - name: prod-device-status-job
              image: eu.gcr.io/airqo-250220/airqo-device-status-job:latest
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: env-device-status-production
              resources:
                limits:
                  cpu: 1000m
                  memory: 4000Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: "*/30 * * * *"
  suspend: false
status: {}
