app:
  name: prod-device-status-job
  namespace: production
  configmap: env-device-status-production

image:
  repository: eu.gcr.io/airqo-250220/airqo-device-status-job
  tag: latest

nameOverride: ""
fullnameOverride: ""
resources:
  limits:
    cpu: 1000m
    memory: 4000Mi
