apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.message-broker.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "view.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
        app: {{ .Values.message-broker.label }}
  replicas: {{ .Values.message-broker.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 10
  template:
    metadata:
      {{- with .Values.message-broker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.message-broker.label }}
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 90
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - high-memory
            - weight: 1
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - general-purpose
      containers:
        - name: {{ .Values.message-broker.label }}
          image: "{{ .Values.message-broker.image.repository }}:{{ .Values.message-broker.image.tag }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ .Values.app.configmap }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config        
      volumes:
        - name: config-volume
          configMap:
            name: view-api-config-files
