###########################################################
# Start deployment of auth api
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-auth-api
  namespace: production
spec:
  selector:
    matchLabels:
      app: auth-api
  replicas: 3
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - high-memory
            - weight: 1
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - general-purpose
      containers:
        - name: auth-api
          image: us.gcr.io/airqo-250220/airqo-auth-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: auth-api
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3000
          #   initialDelaySecond: 5
          #   periodSeconds: 3
          #   successThreshold: 1
          envFrom:
            - configMapRef:
                name: prod-auth-api-config
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          resources:
            requests:
              # Average usage was 0.002 vCPU and 250Mi over the last 30 days
              cpu: 10m
              memory: 250Mi
            limits:
              cpu: 100m
              memory: 350Mi
      volumes:
        - name: config-volume
          configMap:
            name: prod-auth-api-config-files

---
kind: Service
apiVersion: v1
metadata:
  name: airqo-auth-api-svc
  namespace: production
spec:
  selector:
    app: auth-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: airqo-auth-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airqo-auth-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
