###########################################################
# Start deployment of auth api - Staging
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-stage-auth-api
  namespace: staging
spec:
  selector:
    matchLabels:
      app: sta-auth-api
  replicas: 2
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: sta-auth-api
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - high-memory
            - weight: 1
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - general-purpose
      containers:
        - name: sta-auth-api
          image: eu.gcr.io/airqo-250220/airqo-stage-auth-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: sta-auth-api
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3000
          #   initialDelaySecond: 5
          #   periodSeconds: 3
          #   successThreshold: 1
          envFrom:
            - configMapRef:
                name: stage-auth-api-config
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          resources:
            requests:
              # Average usage was 0.002 vCPU and 190Mi over the last 30 days
              cpu: 10m
              memory: 180Mi
            limits:
              cpu: 100m
              memory: 250Mi
      volumes:
        - name: config-volume
          configMap:
            name: stage-auth-api-config-files

---
kind: Service
apiVersion: v1
metadata:
  name: airqo-stage-auth-api-svc
  namespace: staging
spec:
  selector:
    app: sta-auth-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
  type: NodePort

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: airqo-stage-auth-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airqo-stage-auth-api
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
