###########################################################
# Start deployment of calibrate microservice - staging
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-stage-calibrate-api
  namespace: staging
spec:
  selector:
    matchLabels:
      app: sta-calibrate
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: sta-calibrate
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - high-memory
            - weight: 1
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - general-purpose
      initContainers:
        - name: calibrate-pickle
          image: eu.gcr.io/airqo-250220/airqo-stage-calibrate-pickle-file:latest
          imagePullPolicy: Always
          resources: {}
          envFrom:
            - configMapRef:
                name: stage-calibrate-api-config
          env:
            - name: RF_REG_MODEL
              value: /usr/pickle-files/rf_reg_model.pkl
            - name: LASSO_MODEL
              value: /usr/pickle-files/lasso_model.pkl
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: shared-data
              mountPath: /usr/pickle-files
      containers:
        - name: sta-calibrate
          image: eu.gcr.io/airqo-250220/airqo-stage-calibrate-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4001
              name: sta-calibrate
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 4001
          #   initialDelaySecond: 5
          #   periodSeconds: 3
          #   successThreshold: 1
          resources:
            requests:
              # Average usage was 0.0005 vCPU and 200Mi over the last 30 days
              cpu: 10m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 400Mi
          env:
            - name: RF_REG_MODEL
              value: /usr/pickle-files/rf_reg_model.pkl
            - name: LASSO_MODEL
              value: /usr/pickle-files/lasso_model.pkl
          envFrom:
            - configMapRef:
                name: stage-calibrate-api-config
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: shared-data
              mountPath: /usr/pickle-files
      volumes:
        - name: config-volume
          configMap:
            name: stage-calibrate-api-config-files
        - name: shared-data
          emptyDir: {}

---
kind: Service
apiVersion: v1
metadata:
  name: airqo-stage-calibrate-api-svc
  namespace: staging
spec:
  selector:
    app: sta-calibrate
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
      nodePort: 31011
  type: NodePort

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: airqo-stage-calibrate-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airqo-stage-calibrate-api
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
