###########################################################
# Start deployment of view api - production
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-view-api
  namespace: production
spec:
  selector:
    matchLabels:
      app: view-api
  replicas: 2
  minReadySeconds: 90
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: view-api
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
              - key: node-type
                operator: In
                values:
                - high-memory
          - weight: 1
            preference:
              matchExpressions:
              - key: node-type
                operator: In
                values:
                - general-purpose
      containers:
        - name: view-api
          image: us.gcr.io/airqo-250220/airqo-view-api:latest
          imagePullPolicy: Always
          resources:
            requests:
              # Average usage was 0.01 vCPU and 1400Mi over the last 30 days
              cpu: 10m
              memory: 1400Mi
            limits:
              cpu: 100m
              memory: 2500Mi
          ports:
            - containerPort: 8080
              name: view-api
          envFrom:
            - configMapRef:
                name: prod-view-api-config
          readinessProbe:
            initialDelaySeconds: 120
            httpGet:
              port: 8080
              path: api/v1/view/actuator/health/readiness
          livenessProbe:
            initialDelaySeconds: 120
            httpGet:
              port: 8080
              path: api/v1/view/actuator/health/liveness
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]

---
kind: Service
apiVersion: v1
metadata:
  name: airqo-view-api-svc
  namespace: production
spec:
  selector:
    app: view-api
  ports:
    - protocol: TCP
      name: view-api
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: views-api
      port: 8081
      targetPort: 8081

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: airqo-view-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airqo-view-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70