app:
  name: airqo-stage-view-api
  label: view-api
  namespace: staging
  configmap: stage-view-api-config

replicaCount: 2

image:
  repository: gcr.io/airqo-250220/airqo-stage-view-api
  tag: latest

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  limits:
    cpu: 50m
    memory: 700Mi
  requests:
    # Average usage was 0.002 vCPU and 420Mi over the last 30 days
    cpu: 5m
    memory: 420Mi

ingress:
  enabled: false

service:
  type: NodePort
  port: 8080
  protocol: TCP
  targetPort: 8080

autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
