apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "workflows.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
        app: {{ .Values.app.label }}
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.app.label }}
    spec:
      restartPolicy: Always
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - compute
            - weight: 20
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - high-memory
      serviceAccountName: {{ .Values.serviceAccountName }}
      initContainers:
        - name: '{{ .Values.app.name }}-xcom'
          image: "{{ .Values.images.repositories.initContainer }}:{{ .Values.images.tag }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ .Values.app.configmap }} 
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      containers:
        - name: '{{ .Values.app.name }}-scheduler'
          image: "{{ .Values.images.repositories.containers }}:{{ .Values.images.tag }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ .Values.app.configmap }} 
          command: ["airflow"]
          args: ["scheduler"]         
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: '{{ .Values.app.name }}-celery'
          image: "{{ .Values.images.repositories.containers }}:{{ .Values.images.tag }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ .Values.app.configmap }} 
          command: ["airflow"]
          args: ["celery", "worker", "--autoscale=8,3"]         
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: '{{ .Values.app.name }}-webserver'
          image: "{{ .Values.images.repositories.containers }}:{{ .Values.images.tag }}"
          imagePullPolicy: IfNotPresent
          {{- $webTargetPort := include "getTargetPortByName" (list . "web-server") }}
          ports:
            - containerPort: {{ $webTargetPort }}
              name: {{ .Values.app.label }}
          envFrom:
            - configMapRef:
                name: {{ .Values.app.configmap }} 
          command: ["airflow"]
          args: ["webserver"]         
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            initialDelaySeconds: 120
            timeoutSeconds: 120
            httpGet:
              path: /workflows/health
              port: {{ $webTargetPort }}
        - name: '{{ .Values.app.name }}-redis'
          image: "{{ .Values.images.repositories.redisContainer }}:{{ .Values.images.tag }}"
          imagePullPolicy: IfNotPresent
          {{- $redisPort := include "getTargetPortByName" (list . "redis") }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: redis
          envFrom:
            - configMapRef:
                name: {{ .Values.app.configmap }} 
          command: ["redis-server"]         
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 5
            tcpSocket:
              port: {{ $redisPort }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
