apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "workflows.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
        app: {{ .Values.app.label }}
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.app.label }}
    spec:
      restartPolicy: Always
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - compute
            - weight: 20
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - high-memory
      serviceAccountName: {{ .Values.serviceAccountName }}
      initContainers:
        - name: '{{ .Values.app.name }}-xcom'
          image: "{{ .Values.images.repositories.initContainer }}:{{ .Values.images.tag }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ .Values.app.configmap }} 
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: '{{ .Values.app.name }}-dbchecker'
          image: python:3.10.14-slim-bullseye
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c"]
          args:
            - >
              pip install -U pip psycopg2-binary && pip install apache-airflow==2.9.0 && airflow db upgrade
          env:
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.configmap }}
                  key: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN

      containers:
        - name: '{{ .Values.app.name }}-scheduler'
          image: "{{ .Values.images.repositories.containers }}:{{ .Values.images.tag }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ .Values.app.configmap }} 
          command: ["airflow"]
          args: ["scheduler"]         
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: '{{ .Values.app.name }}-webserver'
          image: "{{ .Values.images.repositories.containers }}:{{ .Values.images.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: {{ .Values.app.label }}
          envFrom:
            - configMapRef:
                name: {{ .Values.app.configmap }} 
          command: ["airflow"]
          args: ["webserver"]         
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources: {}
          readinessProbe:
            initialDelaySeconds: 120
            timeoutSeconds: 120
            httpGet:
              path: /workflows/health
              port: 8080
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
