###########################################################
# Start deployment of network uptime api - Production
###########################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-network-uptime-api
  namespace: production
spec:
  selector:
    matchLabels:
      app: prod-network-uptime
  replicas: 3
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: prod-network-uptime
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - general-purpose
      containers:
        - name: prod-network-uptime
          image: us.gcr.io/airqo-250220/airqo-network-uptime-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
              name: prod-net-uptime
          envFrom:
            - configMapRef:
                name: env-network-uptime-production
          resources:
            requests:
              # No available over the last 30 days, using estimates
              cpu: 5m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 200Mi

---
kind: Service
apiVersion: v1
metadata:
  name: airqo-network-uptime-api-svc
  namespace: production
spec:
  selector:
    app: prod-network-uptime
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30012
  type: NodePort

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: airqo-network-uptime-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airqo-network-uptime-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
