apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: "2020-08-13T11:00:12Z"
  managedFields:
    - apiVersion: batch/v1
      manager: kubectl
      operation: Update
      time: "2020-08-13T11:00:12Z"
  name: stage-update-channel-data-job
  namespace: staging
spec:
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: stage-update-channel-data-job
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 10
                  preference:
                    matchExpressions:
                      - key: node-type
                        operator: In
                        values:
                          - compute
          containers:
            - name: stage-update-channel-data-job
              image: us.gcr.io/airqo-250220/airqo-stage-update-channel-data-job:latest
              imagePullPolicy: Always
              resources:
                requests:
                  # Average usage was 0.02 vCPU and 100Mi over the last 30 days
                  cpu: 20m
                  memory: 100Mi
                limits:
                  cpu: 500m
                  memory: 500Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              envFrom:
                - configMapRef:
                    name: env-update-channel-data-staging
              volumeMounts:
                - name: config-volume
                  mountPath: /etc/config
          volumes:
            - name: config-volume
              configMap:
                name: env-update-channel-data-staging-files
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 0 * * * *
  suspend: false
status: {}
