app:
  name: prod-update-channel-data-job
  namespace: production
  configmap: env-update-channel-data-production

image:
  repository: gcr.io/airqo-250220/airqo-update-channel-data-job
  tag: latest

nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    cpu: 500Mi
    memory: 500Mi
  requests:
    # Average usage was 0.02 vCPU and 100Mi over the last 30 days
    cpu: 20m
    memory: 100Mi

volumeMounts:
  - name: config-volume
    mountPath: /etc/config

volumes:
  - name: config-volume
    configMap:
      name: env-update-channel-data-production-files
