apiVersion: v1
kind: Pod
metadata:
  labels:
    airflow-worker: "true"
spec:
  containers:
    - name: airflow-worker
      image: apache/airflow:2.6.3-python3.10
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1"
      env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: "CeleryKubernetesExecutor"
        - name: AIRFLOW__CELERY__BROKER_URL
          value: "redis://redis:6379/0"
        - name: AIRFLOW__CELERY__RESULT_BACKEND
          value: "db+postgresql://airflow:airflow@postgres/airflow"
  restartPolicy: Never
