app:
  name: workflows
  label: workflows
  namespace: pipeline
  configmap: workflows-config
replicaCount: 2
serviceAccountName: workflows-sa
images:
  repositories:
    initContainer: eu.gcr.io/airqo-250220/airqo-workflows-xcom
    containers: eu.gcr.io/airqo-250220/airqo-workflows
  tag: prod-cee8c996-1704500147
nameOverride: ''
fullnameOverride: ''
podAnnotations: {}
resources:
  limits:
    cpu: 1500m
    memory: 4500Mi
  requests:
    cpu: 500m
    memory: 3000Mi
volumeMounts:
  - name: workflows-config-volume
    mountPath: /etc/config
  - name: workflows-xcom-config-volume
    mountPath: /etc/workflows_xcom
volumes:
  - name: workflows-config-volume
    configMap:
      name: workflows-config-files
  - name: workflows-xcom-config-volume
    emptyDir: {}
ingress:
  enabled: false
service:
  type: NodePort
  port: 8080
  protocol: TCP
  targetPort: 8080
  nodePort: 30036
autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
