app:
  name: workflows
  label: workflows
  namespace: pipeline
  configmap: airflow-config
replicaCount: 2
serviceAccountName: stage-airflow-sa
images:
  repositories:
    initContainer: eu.gcr.io/airqo-250220/airqo-stage-workflows-xcom
    redisContainer: eu.gcr.io/airqo-250220/airqo-stage-redis
    containers: eu.gcr.io/airqo-250220/airqo-stage-workflows
  tag: stage-af031d45-1725608963
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
resources:
  webserver:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 1000m
      memory: 1000Mi
  scheduler:
    requests:
      cpu: 1000m
      memory: 2000Mi
    limits:
      cpu: 2000m
      memory: 3000Mi
  celery:
    requests:
      cpu: 1500m
      memory: 1500Mi
    limits:
      cpu: 3000m
      memory: 3000Mi
  redis:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1000Mi
volumeMounts:
  - name: config-volume
    mountPath: /etc/config
  - name: xcom-config-volume
    mountPath: /etc/airflow_xcom
volumes:
  - name: config-volume
    configMap:
      name: airflow-config-files
  - name: xcom-config-volume
    emptyDir: {}
ingress:
  enabled: false
service:
  type: NodePort
  ports:
    - name: web-server
      port: 8080
      targetPort: 8080
      nodePort: 31036
      protocol: TCP
    - name: redis-server
      port: 6379
      targetPort: 6379
      nodePort: 31079
      protocol: TCP
autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
