app:
  name: workflows
  label: workflows
  namespace: pipeline
  configmap: airflow-config
replicaCount: 2
serviceAccountName: airflow-sa
images:
  repositories:
    initContainer: eu.gcr.io/airqo-250220/airqo-workflows-xcom
    redisContainer: eu.gcr.io/airqo-250220/airqo-redis
    containers: eu.gcr.io/airqo-250220/airqo-workflows
  tag: prod-d756fdb5-1724441665
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
resources:
  limits:
    cpu: 2000m
    memory: 6500Mi
  requests:
    cpu: 700m
    memory: 4000Mi
volumeMounts:
  - name: config-volume
    mountPath: /etc/config
  - name: xcom-config-volume
    mountPath: /etc/airflow_xcom
volumes:
  - name: config-volume
    configMap:
      name: airflow-config-files
  - name: xcom-config-volume
    emptyDir: {}
ingress:
  enabled: false
service:
  type: NodePort
  ports:
    - name: web-server
      port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
    - name: redis-server
      port: 6379
      targetPort: 6379
      nodePort: 30079
      protocol: TCP
autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
