app:
  name: airqo-prediction-api
  label: prediction-api
  namespace: production
  configmap: env-predict-production

replicaCount: 3

image:
  repository: gcr.io/airqo-250220/airqo-prediction-api
  tag: latest

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  limits:
    cpu: 50m
    memory: 200Mi
  requests:
    # Average usage was 0.0007 vCPU and 120Mi over the last 30 days
    cpu: 5m
    memory: 120Mi

volumeMounts:
  - name: config-volume
    mountPath: /etc/config

volumes:
  - name: config-volume
    configMap:
      name: env-predict-production-files

ingress:
  enabled: false

service:
  type: NodePort
  port: 5000
  protocol: TCP
  targetPort: 5000
  nodePort: 30009

autoscaling:
  minReplicas: 1
  maxReplicas: 3
  # targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
