app:
  name: airqo-stage-prediction-api
  label: prediction-api
  namespace: staging
  configmap: env-predict-staging

replicaCount: 2

image:
  repository: gcr.io/airqo-250220/airqo-stage-prediction-api
  tag: latest

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  limits:
    cpu: 50m
    memory: 200Mi
  requests:
    # Average usage was 0.0006 vCPU and 140Mi over the last 30 days
    cpu: 5m
    memory: 130Mi

volumeMounts:
  - name: config-volume
    mountPath: /etc/config

volumes:
  - name: config-volume
    configMap:
      name: env-predict-staging-files

ingress:
  enabled: false

service:
  type: NodePort
  port: 5000
  protocol: TCP
  targetPort: 5000
  nodePort: 31009

autoscaling:
  minReplicas: 1
  maxReplicas: 2
  # targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
