###########################################################
# Start deployment of analytics api
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-analytics-api
  namespace: production
spec:
  selector:
    matchLabels:
      app: analytics-api
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: analytics-api
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
              - key: node-type
                operator: In
                values:
                - high-memory  
          - weight: 1
            preference:
              matchExpressions:
              - key: node-type
                operator: In
                values:
                - general-purpose  
      containers:
        - name: analytics-api
          image: us.gcr.io/airqo-250220/airqo-analytics-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: analytics-api
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 5000
          #   initialDelaySecond: 5
          #   periodSeconds: 3
          #   successThreshold: 1
          envFrom:
            - configMapRef:
                name: env-analytics-production
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config
          resources:
            requests:
              # Average usage was 0.001 vCPU and 250Mi over the last 30 days
              cpu: 10m
              memory: 250Mi
            limits:
              cpu: 100m
              memory: 400Mi
      volumes:
        - name: config-volume
          configMap:
            name: prod-analytics-config-files

---
kind: Service
apiVersion: v1
metadata:
  name: airqo-analytics-api-svc
  namespace: production
spec:
  selector:
    app: analytics-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30003
  type: NodePort

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: airqo-analytics-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airqo-analytics-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70