###########################################################
# Start deployment of analytics api - Staging
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-stage-analytics-api
  namespace: staging
spec:
  selector:
    matchLabels:
      app: sta-alytics-api
  replicas: 2
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: sta-alytics-api
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - high-memory
            - weight: 1
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - general-purpose
      containers:
        - name: sta-alytics-api
          image: eu.gcr.io/airqo-250220/airqo-stage-analytics-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: sta-alytics-api
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 5000
          #   initialDelaySecond: 5
          #   periodSeconds: 3
          #   successThreshold: 1
          envFrom:
            - configMapRef:
                name: env-analytics-staging
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          resources:
            requests:
              # Average usage was 0.001 vCPU and 250Mi over the last 30 days
              cpu: 10m
              memory: 250Mi
            limits:
              cpu: 100m
              memory: 400Mi
      volumes:
        - name: config-volume
          configMap:
            name: stage-analytics-config-files

---
kind: Service
apiVersion: v1
metadata:
  name: airqo-stage-analytics-api-svc
  namespace: staging
spec:
  selector:
    app: sta-alytics-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31003
  type: NodePort

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: airqo-stage-analytics-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airqo-stage-analytics-api
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
