namespace: staging
nameOverride: ''
fullnameOverride: ''
images:
  repositories:
    api: eu.gcr.io/airqo-250220/airqo-stage-analytics-api
    celery: eu.gcr.io/airqo-250220/airqo-stage-analytics-celery-worker
    devicesSummaryJob: eu.gcr.io/airqo-250220/airqo-stage-analytics-devices-summary-job
  tag: stage-96d94ce4-1715349509
api:
  name: airqo-stage-analytics-api
  label: sta-alytics-api
  configmap: env-analytics-staging
  replicaCount: 2
  podAnnotations: {}
  resources:
    limits:
      cpu: 100m
      memory: 600Mi
    requests:
      cpu: 10m
      memory: 250Mi
jobs:
  devicesSummaryJob:
    name: stage-analytics-devices-summary
    configmap: env-analytics-staging
  resources:
    limits:
      cpu: 1000m
      memory: 4000Mi
volumeMounts:
  - name: config-volume
    mountPath: /etc/config
volumes:
  - name: config-volume
    configMap:
      name: stage-analytics-config-files
service:
  type: NodePort
  port: 5000
  protocol: TCP
  targetPort: 5000
  nodePort: 31003
ingress:
  enabled: false
autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetMemoryUtilizationPercentage: 80
