namespace: production
nameOverride: ''
fullnameOverride: ''
images:
  repositories:
    api: eu.gcr.io/airqo-250220/airqo-analytics-api
    celery: eu.gcr.io/airqo-250220/airqo-analytics-celery
  tag: prod-d02063d6-1715359227
api:
  name: airqo-analytics-api
  label: analytics-api
  configmap: env-analytics-production
  replicaCount: 3
  podAnnotations: {}
  resources:
    limits:
      cpu: 100m
      memory: 600Mi
    requests:
      cpu: 10m
      memory: 250Mi
volumeMounts:
  - name: config-volume
    mountPath: /etc/config
volumes:
  - name: config-volume
    configMap:
      name: prod-analytics-config-files
service:
  type: NodePort
  port: 5000
  protocol: TCP
  targetPort: 5000
  nodePort: 30003
ingress:
  enabled: false
autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetMemoryUtilizationPercentage: 70
