replicaCount: 2
image:
  repository: ghcr.io/mlflow/mlflow
  pullPolicy: IfNotPresent
  tag: ""
nameOverride: ""
fullnameOverride: ""
service:
  type: NodePort
  port: 5024

backendStore:
  databaseConnectionCheck: true
  postgres:
    enabled: true
    driver: "psycopg2"

artifactRoot:
  gcs:
    enabled: true
    bucket: "airqo-mlflow-artifacts"
    path: ""

resources:
  limits:
    cpu: 1000m
    memory: 2000Mi
  requests:
    cpu: 800m
    memory: 1500Mi

extraVolumes:
  - name: mlflow-pv
    persistentVolumeClaim:
      claimName: mlflow-pv

extraVolumeMounts:
  - name: mlflow-pv
    mountPath: /mlflow-volumes/
