apiVersion: batch/v1
kind: CronJob
metadata:
  name: airqo-train-job
  namespace: production
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "0 5 * * 1"
  jobTemplate:
    metadata:
      name: airqo-train-job
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 10
                  preference:
                    matchExpressions:
                      - key: node-type
                        operator: In
                        values:
                          - compute
          containers:
            - name: airqo-train-job
              image: us.gcr.io/airqo-250220/airqo-train-job:latest
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: env-train-job-production
              volumeMounts:
                - name: config-volume
                  mountPath: /etc/config
              resources:
                limits:
                  # Has had an average CPU throttling rate of 30% of 2000m in the last 30 days
                  cpu: 2500m
                  memory: 4000Mi
          volumes:
            - name: config-volume
              configMap:
                name: train-job-config-files
