apiVersion: batch/v1
kind: CronJob
metadata:
  name: airqo-predict-job
  namespace: production
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "0 * * * *"
  jobTemplate:
    metadata:
      name: airqo-predict-job
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 10
                  preference:
                    matchExpressions:
                      - key: node-type
                        operator: In
                        values:
                          - compute
          containers:
            - name: airqo-predict-job
              image: eu.gcr.io/airqo-250220/airqo-predict-job:latest
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: env-predict-job-production
              volumeMounts:
                - name: config-volume
                  mountPath: /etc/config
              resources:
                limits:
                  cpu: 1000m
                  memory: 4000Mi
          volumes:
            - name: config-volume
              configMap:
                name: predict-job-config-files
