apiVersion: batch/v1
kind: CronJob
metadata:
  name: stage-airqo-predict-job
  namespace: staging
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "0 * * * *"
  jobTemplate:
    metadata:
      name: stage-airqo-predict-job
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 10
                preference:
                  matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                    - compute
          containers:
          - name: stage-airqo-predict-job
            image: us.gcr.io/airqo-250220/stage-airqo-predict-job:latest
            imagePullPolicy: Always
            envFrom:
              - configMapRef:
                  name: env-predict-job-staging
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
            resources:
              limits:
                cpu: 1000m
                memory: 4000Mi
          volumes:
            - name: config-volume
              configMap:
                name: predict-job-config-files
