###########################################################
# Start deployment of prediction api
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-stage-prediction-api
  namespace: staging
spec:
  selector:
    matchLabels:
      app: prediction-api
  replicas: 2
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: prediction-api
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - general-purpose
      containers:
        - name: prediction-api
          image: us.gcr.io/airqo-250220/airqo-stage-prediction-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: prediction-api
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 5000
          #   initialDelaySecond: 5
          #   periodSeconds: 3
          #   successThreshold: 1
          envFrom:
            - configMapRef:
                name: env-predict-staging
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          resources:
            requests:
              # Average usage was 0.0006 vCPU and 140Mi over the last 30 days
              cpu: 5m
              memory: 130Mi
            limits:
              cpu: 50m
              memory: 200Mi
      volumes:
        - name: config-volume
          configMap:
            name: env-predict-staging-files

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: airqo-stage-prediction-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airqo-stage-prediction-api
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---
kind: Service
apiVersion: v1
metadata:
  name: airqo-stage-prediction-api-svc
  namespace: staging
spec:
  selector:
    app: prediction-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31009
  type: NodePort
