apiVersion: v2
appVersion: "1.16.0"
description: AirQo predict places air quality job Helm Chart
name: airqo-train-job
home: https://airqo.net
version: 0.1.0
maintainers:
  - name: AirQo
    email: support@airqo.net
    url: https://airqo.net
