app:
  name: airqo-predict-places-air-quality
  namespace: production
  configmap: env-predict-places-air-quality-production
schedule: 30 * * * *
suspend: true
image:
  repository: eu.gcr.io/airqo-250220/airqo-predict-places-air-quality
  tag: prod-24564183-164739284
nameOverride: ''
fullnameOverride: ''
resources:
  limits:
    cpu: 8000m
    memory: 16000Mi
  requests:
    cpu: 2500m
    memory: 4000Mi
volumeMounts:
  - name: config-volume
    mountPath: /etc/config
volumes:
  - name: config-volume
    configMap:
      name: predict-places-air-quality-config-files
