app:
  name: stage-airqo-predict-places-air-quality
  namespace: staging
  configmap: env-predict-places-air-quality-staging
schedule: 30 * * * *
suspend: true
image:
  repository: eu.gcr.io/airqo-250220/stage-airqo-predict-places-air-quality
  tag: stage-24564183-164739284
nameOverride: ''
fullnameOverride: ''
resources:
  limits:
    cpu: 2500m
    memory: 4000Mi
volumeMounts:
  - name: config-volume
    mountPath: /etc/config
volumes:
  - name: config-volume
    configMap:
      name: predict-places-air-quality-config-files
