app:
  name: prod-device-uptime-job
  namespace: production
  configmap: env-device-uptime-production
image:
  repository: eu.gcr.io/airqo-250220/airqo-device-uptime-job
  tag: prod-cafcca31-1678883897
nameOverride: ''
fullnameOverride: ''
resources:
  limits:
    cpu: 1000m
    memory: 4000Mi
