app:
  name: airqo-incentives-api
  label: incentives-api
  namespace: production
  configmap: incentives-api-config
replicaCount: 3
image:
  repository: eu.gcr.io/airqo-250220/airqo-incentives-api
  tag: latest
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
resources: 
  limits:
    cpu: 1000m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 250Mi
volumeMounts:
  - name: config-volume
    mountPath: /etc/config
volumes:
  - name: config-volume
    configMap:
      name: prod-incentives-api-config-files    
ingress:
  enabled: false
service:
  type: NodePort
  port: 3000
  protocol: TCP
  targetPort: 3000
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


