###########################################################
# Start deployment of locate api
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-locate-api
  namespace: production
spec:
  selector:
    matchLabels:
      app: locate-api
  replicas: 3
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: locate-api
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - general-purpose
            - weight: 1
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - high-memory
      containers:
        - name: locate-api
          image: us.gcr.io/airqo-250220/airqo-locate-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4001
              name: locate-api
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 4001
          #   initialDelaySecond: 5
          #   periodSeconds: 3
          #   successThreshold: 1
          envFrom:
            - configMapRef:
                name: env-locate-production
          resources:
            requests:
              # Average usage was 0.001 vCPU and 300Mi over the last 30 days
              cpu: 5m
              memory: 300Mi
            limits:
              cpu: 50m
              memory: 500Mi

---
kind: Service
apiVersion: v1
metadata:
  name: airqo-locate-api-svc
  namespace: production
spec:
  selector:
    app: locate-api
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
      nodePort: 30004
  type: NodePort

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: airqo-locate-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airqo-locate-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
