###########################################################
# Start deployment of locate api - staging
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-stage-locate-api
  namespace: staging
spec:
  selector:
    matchLabels:
      app: sta-locate-api
  replicas: 2
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: sta-locate-api
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - general-purpose
            - weight: 1
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - high-memory
      containers:
        - name: sta-locate-api
          image: eu.gcr.io/airqo-250220/airqo-stage-locate-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4001
              name: sta-locate-api
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 4001
          #   initialDelaySecond: 5
          #   periodSeconds: 3
          #   successThreshold: 1
          envFrom:
            - configMapRef:
                name: env-locate-staging
          resources:
            requests:
              # Average usage was 0.001 vCPU and 80Mi over the last 30 days
              cpu: 5m
              memory: 80Mi
            limits:
              cpu: 50m
              memory: 120Mi
---
kind: Service
apiVersion: v1
metadata:
  name: airqo-stage-locate-api-svc
  namespace: staging
spec:
  selector:
    app: sta-locate-api
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
      nodePort: 31004
  type: NodePort

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: airqo-stage-locate-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airqo-stage-locate-api
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
