app:
  name: airqo-stage-locate-api
  label: sta-locate-api
  namespace: staging
  configmap: env-locate-staging

replicaCount: 2

image:
  repository: eu.gcr.io/airqo-250220/airqo-stage-locate-api
  tag: latest

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  limits:
    cpu: 50m
    memory: 120Mi
  requests:
    # Average usage was 0.0005 vCPU and 200Mi over the last 30 days
    cpu: 5m
    memory: 80Mi

ingress:
  enabled: false

service:
  type: NodePort
  port: 4001
  protocol: TCP
  targetPort: 4001
  nodePort: 31004

autoscaling:
  minReplicas: 1
  maxReplicas: 2
  # targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
